spring.jpa.properties.hibernate.default_schema=public
spring.datasource.url=jdbc:postgresql://localhost:5432/taxi
spring.datasource.username=postgres
spring.datasource.password=keill1270
spring.datasource.driver-class-name=org.postgresql.Driver
spring.messages.encoding=UTF-8
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false